### ISSUE TITLE
Push to Nuvola Apps project

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvola-app-jupiter-broadcasting#1]
As per service integration instructions.

**Comment by jiri-janousek** [comment]
Thanks @a-m-s for your work. Do you need to support Nuvola 3 (EOL 12/31/2017) as well? I no longer create any new web app packages for it but there may be third-party builds. You could get rid of a few `if Nuvola.checkVersion` if you increased API to 4.6. (I've just updated developer docs to use 4.6 and Nuvola SDK/ADK will be updated as well.)

Anyway, you can [transfer your repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization) to the  [Nuvola Maintainers](https://github.com/orgs/tiliado/teams/nuvola-maintainers/members) team and I'll build flatpaks 👍

**Comment by a-m-s** [comment]
Done.

BTW, I'll be away from my computer for the next week.

**Comment by jiri-janousek** [comment]
🎉 Flatpak built 👍
