### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvola-app-jupiter-broadcasting#5]
New features:
* Choose Linux podcast.

Bug fixes:
* Volume controls now work.

**Comment by jiri-janousek** [comment]
Awesome :+1:  I've just published rebuilt Flatpaks. I'll make a formal release with Nuvola 4.16 later this month.

**Comment by jiri-janousek** [comment]
Released with **Nuvola 4.16.0**, more info: [Nuvola 4.16 Brings Libre.FM Scrobbling, Ivoox Service, and more](https://medium.com/nuvola-news/nuvola-4-16-86a089068784)
