### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvola-app-jupiter-broadcasting#6]
* Update following JB site redesign.
  * Add the Friday Stream.

**Comment by jiri-janousek** [comment]
I've published new flatpaks with latest git master.

**Comment by a-m-s** [comment]
I'm not sure what happened to this?

I've now added more for release:

  * Add Jupiter Extras.
  * Add Linux Headlines.

**Comment by jiri-janousek** [comment]
Cool. I hope to make a new Nuvola release this month. Flatpak builds has started failing last week so I need to figure out what's wrong. That's the very last blocker.

**Comment by jiri-janousek** [comment]
Release 1.5 tagged and will be announced later today.
